import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ClaimsHttpInterceptorService implements HttpInterceptor {
  
  constructor() { }
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    //Get Token
    const token ="Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjBteDFLemF0VC1nQ1JiRkliaTJMaVdod0FyNzdLdzhhajhPSVB0LVlyVGMiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xYjFlYzE4Yi1mN2IzLTRhMmUtOGIyMC1kOWZhNTgwZjFmNzUvIiwiaWF0IjoxNjk2Nzg2NTY1LCJuYmYiOjE2OTY3ODY1NjUsImV4cCI6MTY5Njc5MjEzOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFYUUFpLzhVQUFBQUdRcldFVGFvREs0OEx4UmUveTYrSFhVZ1pqQlVvMDQ4SHZ4aHhUNWdkZHFwdW0vbWU4VDB3blJLUGhZQ2tpS3ZHQWsrNUswMkZjSlIzWlVTeCtOaEFYL0JBOURqaEZXTUZUTzlGdk1kaUtvbWdORkpSRXF0SFNQVDhhcGJPUFFPd3NkZmUzQjFCUENGNTd2Ulc2Y2V5UT09IiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEMkIxM0VFQTMiLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcF9kaXNwbGF5bmFtZSI6ImNsYWltc0NsaWVudCIsImFwcGlkIjoiMjJjMjEyOWItZjNlYi00ZWJlLWI0NjctMTRjNGEyZTVjOTVhIiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJpYXJzaGFkQG91dGxvb2suZGUiLCJmYW1pbHlfbmFtZSI6Ikh1c3NlaW4iLCJnaXZlbl9uYW1lIjoiQXJzaGFkIiwiaWRwIjoibGl2ZS5jb20iLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMDAzOjY6MzMzNzoyZmM5OmUxY2M6MzhlMTo1MDdjOjUyNWEiLCJuYW1lIjoiQXJzaGFkIEh1c3NlaW4iLCJvaWQiOiI3YzhmM2FhYS0xMjI0LTRiODctODNhYi00OTJjYzFjZmEwMTQiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzIwMDBCMDdGMzk5MSIsInJoIjoiMC5BVjRBaThFZUc3UDNMa3FMSU5uNldBOGZkUU1BQUFBQUFBQUF3QUFBQUFBQUFBQmVBRHcuIiwic2NwIjoib3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic3ViIjoiWlNGLVU4MEtBamR0ckZmMDBvekk5ZjJxUWFxX3poQzZqSmJNSG1HdVo0SSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6IjFiMWVjMThiLWY3YjMtNGEyZS04YjIwLWQ5ZmE1ODBmMWY3NSIsInVuaXF1ZV9uYW1lIjoibGl2ZS5jb20jaWFyc2hhZEBvdXRsb29rLmRlIiwidXRpIjoiWW5HcXVOREF6RWE5azBwN2pYMmdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJPYTlzcXVYSU5pVnlKcWZzRzQ0czBFTmNtTm42aEw4QXAxZ0VZTVhMSy13In0sInhtc190Y2R0IjoxNTg2ODcyNTQxLCJ4bXNfdGRiciI6IkVVIn0.H7wSsPpSocXWFF41DVH2RhpLVAB_dLsOKNtMEKtFrqBy1HAE9GeuwS-tcVNakTok7vCy1rLjU1JMuGcXPrhwe7pU38jfELee0vOx8FEE2Q1ogAuDWofpsq9XxssfjeTLRfJUBAw0Pm48Qq_0SEVOBB_Be5mmfY7MG0hJ8inxpNfr27IID9RyUqZNlzNY4TCR97EsRPD9vvQ3TLQILIGoGJgvZmOWJS-4EnWwvGaPkReKHGAuKTHH_g_1EEt9og2EKtfH00fyl2JZRcTRFfObFlQvylm0oVQGjG36TeLpD7ctbFh_BKowZmtNBMEOZ8TthWsdHR7ILxOqUxUOB01Knw"
    //let sessionObj = sessionStorage.getItem("authResponse")?.toString() || "";
    req = req.clone({
      setHeaders: {
        'Content-Type' : 'application/json; charset=utf-8',
        'Accept'       : 'application/json',
        'Authorization': `${token}`,
      },
    });
    return next.handle(req)
  }
}
